security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MY\EntityBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        chain_provider:
              chain:
                  providers: [fos_userbundle, fos_facebook_provider]
        main:
            entity: { class: MYEntityBundle:User }

        fos_userbundle:
            id: fos_user.user_provider.username

        fos_facebook_provider:
            id: facebook_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/.*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: _security_check
                login_path: _login
            logout:
                path:   _logout
            anonymous: true

    access_control:
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/security_test, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
